import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const read = (path) => readFileSync(path, "utf8");

const sectionBetween = (source, start, end) => {
  const startIndex = source.indexOf(start);
  const endIndex = source.indexOf(end);

  assert.notEqual(startIndex, -1, `${start} section should exist`);
  assert.notEqual(endIndex, -1, `${end} section should exist`);
  assert.ok(startIndex < endIndex, `${start} should appear before ${end}`);

  return source.slice(startIndex, endIndex);
};

test("repository contains the GitHub-native workflow guide and templates", () => {
  const requiredFiles = [
    "AGENTS.md",
    "docs/github-agent-workflow.md",
    ".github/ISSUE_TEMPLATE/agent-task.yml",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/pull_request_template.md",
    ".github/workflows/deploy-pages.yml",
    ".github/workflows/readiness-audit.yml",
    "GITHUB_PAGES_3D_AGENT_DESIGN.md",
  ];

  for (const path of requiredFiles) {
    assert.equal(existsSync(path), true, `${path} should exist`);
  }
});

test("workflow guide defines the GitHub-native operating model", () => {
  const guide = read("docs/github-agent-workflow.md");

  const requiredPhrases = [
    "Project Status = Ready",
    "agent-ready",
    "Planner Chat",
    "Orchestrator Chat",
    "Worker Chat",
    "GitHub Issue",
    "GitHub Projects",
    "Closes #",
    "GitHub Pages",
    "New project integration",
    "Existing project integration",
    "Existing project with Linear",
    "Existing project without agent workflow",
    "Linear workflow audit",
    "Linear-to-GitHub mapping",
    "No-tooling bootstrap",
    "Planner setup prompt",
    "Orchestrator queue prompt",
    "Worker delivery prompt",
    "Human creates only Brainstorm Chat, Planner Chat, and Orchestrator Chat",
    "Orchestrator creates GitHub Issues",
    "Issue Form is fallback",
    "Worker packet is generated by Orchestrator",
    "QA block is verified by Orchestrator",
    "GitHub tools / gh / GitHub API",
    "GitHub Setup Packet",
    "Orchestrator applies GitHub setup",
    "gh repo edit --enable-issues --enable-projects",
    "gh label create",
    "gh project field-create",
    "Human action required",
    "Max worker tasks per Orchestrator Chat: 5",
    "heartbeat every 20-30 minutes",
    "DRAINING",
    "RETIRED",
    "handoff YAML",
    "takeover audit",
    "Model Router",
    "Graphify or fallback repository tracing",
    "TDD RED/GREEN",
    "QA subagents",
    "Worker completion report",
    "Process Improvement",
  ];

  for (const phrase of requiredPhrases) {
    assert.match(guide, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${phrase} should be documented`);
  }
});

test("site source presents the workflow and GitHub Pages answer", () => {
  const app = read("src/App.tsx");

  const requiredPhrases = [
    "GitHub-native agent workflow",
    "Readiness gate",
    "Planner",
    "Orchestrator",
    "Worker",
    "Issue Forms",
    "GitHub Actions",
    "GitHub Pages",
    "New project setup",
    "Existing project integration",
    "Existing project with Linear",
    "Existing project without agent workflow",
    "Linear workflow audit",
    "Linear-to-GitHub mapping",
    "No-tooling bootstrap",
    "Copy/paste prompts",
    "Canonical MD template",
    "Full canonical GitHub workflow markdown",
    "Planner setup prompt",
    "Orchestrator queue prompt",
    "Worker delivery prompt",
    "Human creates only Brainstorm Chat, Planner Chat, and Orchestrator Chat",
    "Orchestrator creates GitHub Issues",
    "Issue Form is fallback",
    "Worker packet is generated by Orchestrator",
    "QA block is verified by Orchestrator",
    "GitHub tools / gh / GitHub API",
    "GitHub Setup Packet",
    "Orchestrator applies GitHub setup",
    "gh repo edit --enable-issues --enable-projects",
    "gh label create",
    "gh project field-create",
    "Human action required",
    "Max worker tasks per Orchestrator Chat: 5",
    "heartbeat every 20-30 minutes",
    "DRAINING",
    "handoff YAML",
    "Model Router",
    "Graphify or fallback repository tracing",
    "TDD RED/GREEN",
    "QA subagents",
    "Worker completion report",
  ];

  for (const phrase of requiredPhrases) {
    assert.match(app, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${phrase} should be visible in App.tsx`);
  }
});

test("workflow guide and site document adoption scenarios", () => {
  const guide = read("docs/github-agent-workflow.md");
  const app = read("src/App.tsx");

  const scenarioPhrases = [
    "Existing project with Linear",
    "Existing project without agent workflow",
    "Linear workflow audit",
    "Linear-to-GitHub mapping",
    "No-tooling bootstrap",
    "GitHub Setup Packet",
    "Human action required",
  ];

  for (const phrase of scenarioPhrases) {
    const escaped = phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    assert.match(guide, new RegExp(escaped), `${phrase} should be documented in the canonical guide`);
    assert.match(app, new RegExp(escaped), `${phrase} should be visible in the site source`);
  }
});

test("workflow guide groups stage prompts under each instruction type", () => {
  const guide = read("docs/github-agent-workflow.md");

  const promptGroups = [
    {
      start: "## New project integration",
      end: "## Existing project integration",
      marker: "### New project prompts",
    },
    {
      start: "## Existing project integration",
      end: "## Existing project with Linear",
      marker: "### Existing project prompts",
    },
    {
      start: "## Existing project with Linear",
      end: "## Existing project without agent workflow",
      marker: "### Linear project prompts",
    },
    {
      start: "## Existing project without agent workflow",
      end: "## Copy/Paste Prompts",
      marker: "### No-tooling bootstrap prompts",
    },
  ];

  const stageHeadings = [
    "#### Brainstorm prompt",
    "#### Planner prompt",
    "#### Orchestrator prompt",
    "#### Worker prompt",
    "#### QA verification prompt",
  ];

  for (const group of promptGroups) {
    const section = sectionBetween(guide, group.start, group.end);
    assert.match(section, new RegExp(group.marker.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${group.marker} should be inside ${group.start}`);

    for (const heading of stageHeadings) {
      assert.match(section, new RegExp(heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${heading} should be inside ${group.start}`);
    }
  }
});

test("site groups prompt cards by instruction type", () => {
  const app = read("src/App.tsx");

  const requiredPhrases = [
    "const instructionTypes",
    "New project prompts",
    "Existing project prompts",
    "Linear project prompts",
    "No-tooling bootstrap prompts",
    "Brainstorm prompt",
    "Planner prompt",
    "Orchestrator prompt",
    "Worker prompt",
    "QA verification prompt",
  ];

  for (const phrase of requiredPhrases) {
    assert.match(app, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${phrase} should be present in App.tsx`);
  }

  assert.doesNotMatch(app, /const prompts: PromptBlock\[\]/, "site should not keep one global prompt list");
});

test("site embeds the full canonical markdown guide", () => {
  const app = read("src/App.tsx");

  const requiredPhrases = [
    "../docs/github-agent-workflow.md?raw",
    "Canonical MD template",
    "Full canonical GitHub workflow markdown",
    "docs/github-agent-workflow.md",
    "canonical-source",
    "value={canonicalMarkdown}",
  ];

  for (const phrase of requiredPhrases) {
    assert.match(app, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${phrase} should be embedded in App.tsx`);
  }
});

test("Vite config uses the GitHub Pages project base path", () => {
  const config = read("vite.config.ts");

  assert.match(config, /base:\s*["']\/agent_workflow_guide_github_solutions\/["']/);
});

test("GitHub templates require canonical worker evidence", () => {
  const issueForm = read(".github/ISSUE_TEMPLATE/agent-task.yml");
  const prTemplate = read(".github/pull_request_template.md");

  const issueRequiredPhrases = [
    "Model Router",
    "Graphify or fallback repository tracing",
    "TDD RED/GREEN",
    "QA subagents",
    "Primary signal",
  ];

  const prRequiredPhrases = [
    "TDD RED/GREEN evidence",
    "Graphify or fallback repository tracing",
    "QA subagents",
    "Worker completion report",
    "Primary signal status",
    "Secondary signal status",
  ];

  for (const phrase of issueRequiredPhrases) {
    assert.match(issueForm, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${phrase} should be required by the issue form`);
  }

  for (const phrase of prRequiredPhrases) {
    assert.match(prTemplate, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${phrase} should be required by the PR template`);
  }
});
