import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const read = (path) => readFileSync(path, "utf8");

test("repository contains the GitHub-native workflow guide and templates", () => {
  const requiredFiles = [
    "AGENTS.md",
    "docs/github-agent-workflow.md",
    ".github/ISSUE_TEMPLATE/agent-task.yml",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/pull_request_template.md",
    ".github/workflows/deploy-pages.yml",
    ".github/workflows/readiness-audit.yml",
    "GITHUB_PAGES_3D_AGENT_DESIGN.md",
  ];

  for (const path of requiredFiles) {
    assert.equal(existsSync(path), true, `${path} should exist`);
  }
});

test("workflow guide defines the GitHub-native operating model", () => {
  const guide = read("docs/github-agent-workflow.md");

  const requiredPhrases = [
    "Project Status = Ready",
    "agent-ready",
    "Planner Chat",
    "Orchestrator Chat",
    "Worker Chat",
    "GitHub Issue",
    "GitHub Projects",
    "Closes #",
    "GitHub Pages",
    "New project integration",
    "Existing project integration",
    "Planner setup prompt",
    "Orchestrator queue prompt",
    "Worker delivery prompt",
    "Human creates only Brainstorm Chat, Planner Chat, and Orchestrator Chat",
    "Orchestrator creates GitHub Issues",
    "Issue Form is fallback",
    "Worker packet is generated by Orchestrator",
    "QA block is verified by Orchestrator",
    "GitHub tools / gh / GitHub API",
    "GitHub Setup Packet",
    "Orchestrator applies GitHub setup",
    "gh repo edit --enable-issues --enable-projects",
    "gh label create",
    "gh project field-create",
    "Human action required",
    "Max worker tasks per Orchestrator Chat: 5",
    "heartbeat every 20-30 minutes",
    "DRAINING",
    "RETIRED",
    "handoff YAML",
    "takeover audit",
    "Model Router",
    "Graphify or fallback repository tracing",
    "TDD RED/GREEN",
    "QA subagents",
    "Worker completion report",
    "Process Improvement",
  ];

  for (const phrase of requiredPhrases) {
    assert.match(guide, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${phrase} should be documented`);
  }
});

test("site source presents the workflow and GitHub Pages answer", () => {
  const app = read("src/App.tsx");

  const requiredPhrases = [
    "GitHub-native agent workflow",
    "Readiness gate",
    "Planner",
    "Orchestrator",
    "Worker",
    "Issue Forms",
    "GitHub Actions",
    "GitHub Pages",
    "New project setup",
    "Existing project integration",
    "Copy/paste prompts",
    "Canonical MD template",
    "Full canonical GitHub workflow markdown",
    "Planner setup prompt",
    "Orchestrator queue prompt",
    "Worker delivery prompt",
    "Human creates only Brainstorm Chat, Planner Chat, and Orchestrator Chat",
    "Orchestrator creates GitHub Issues",
    "Issue Form is fallback",
    "Worker packet is generated by Orchestrator",
    "QA block is verified by Orchestrator",
    "GitHub tools / gh / GitHub API",
    "GitHub Setup Packet",
    "Orchestrator applies GitHub setup",
    "gh repo edit --enable-issues --enable-projects",
    "gh label create",
    "gh project field-create",
    "Human action required",
    "Max worker tasks per Orchestrator Chat: 5",
    "heartbeat every 20-30 minutes",
    "DRAINING",
    "handoff YAML",
    "Model Router",
    "Graphify or fallback repository tracing",
    "TDD RED/GREEN",
    "QA subagents",
    "Worker completion report",
  ];

  for (const phrase of requiredPhrases) {
    assert.match(app, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${phrase} should be visible in App.tsx`);
  }
});

test("site embeds the full canonical markdown guide", () => {
  const app = read("src/App.tsx");

  const requiredPhrases = [
    "../docs/github-agent-workflow.md?raw",
    "Canonical MD template",
    "Full canonical GitHub workflow markdown",
    "docs/github-agent-workflow.md",
    "canonical-source",
    "value={canonicalMarkdown}",
  ];

  for (const phrase of requiredPhrases) {
    assert.match(app, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${phrase} should be embedded in App.tsx`);
  }
});

test("Vite config uses the GitHub Pages project base path", () => {
  const config = read("vite.config.ts");

  assert.match(config, /base:\s*["']\/agent_workflow_guide_github_solutions\/["']/);
});

test("GitHub templates require canonical worker evidence", () => {
  const issueForm = read(".github/ISSUE_TEMPLATE/agent-task.yml");
  const prTemplate = read(".github/pull_request_template.md");

  const issueRequiredPhrases = [
    "Model Router",
    "Graphify or fallback repository tracing",
    "TDD RED/GREEN",
    "QA subagents",
    "Primary signal",
  ];

  const prRequiredPhrases = [
    "TDD RED/GREEN evidence",
    "Graphify or fallback repository tracing",
    "QA subagents",
    "Worker completion report",
    "Primary signal status",
    "Secondary signal status",
  ];

  for (const phrase of issueRequiredPhrases) {
    assert.match(issueForm, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${phrase} should be required by the issue form`);
  }

  for (const phrase of prRequiredPhrases) {
    assert.match(prTemplate, new RegExp(phrase.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")), `${phrase} should be required by the PR template`);
  }
});
