import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import canonicalMarkdown from "../docs/github-agent-workflow.md?raw";
import { supportsWebGL } from "./three/webglSupport";

const ThreeHeroCanvas = lazy(() => import("./three/ThreeHeroCanvas"));

type Card = {
  title: string;
  copy: string;
};

type Step = {
  title: string;
  copy: string;
};

type PromptBlock = {
  title: string;
  copy: string;
  prompt: string;
};

const capabilities: Card[] = [
  {
    title: "GitHub Issues as the contract",
    copy: "Each task carries goal, acceptance criteria, blockers, validation, security, design, and QA state in one reviewable record.",
  },
  {
    title: "GitHub Projects as the queue",
    copy: "Status, work type, risk, and QA fields replace Linear queue state while labels keep routing simple for agents.",
  },
  {
    title: "GitHub Actions as guardrails",
    copy: "Pages deployment and readiness audit workflows protect the system without turning the static site into a backend.",
  },
  {
    title: "PR evidence as the handoff",
    copy: "Every Worker PR links the issue with Closes #, captures acceptance evidence, and records validation before merge.",
  },
];

const flow = [
  ["01", "Planner", "Define templates, labels, project schema, and issue-sized work."],
  [
    "02",
    "Orchestrator",
    "Run heartbeat every 20-30 minutes, inspect blockers, call Model Router, and start one worker per issue.",
  ],
  ["03", "Worker", "Use TDD RED/GREEN, grounding, QA subagents, and one evidence-rich pull request."],
  ["04", "GitHub Pages", "Publish the operating model as a static presentation, not as orchestration state."],
];

const controlPlane: Step[] = [
  {
    title: "Human creates only Brainstorm Chat, Planner Chat, and Orchestrator Chat",
    copy: "Как и в Linear-инструкции, человек не создает Worker packets, QA chats или обычные delivery issues вручную. Он запускает только три управляющих чата.",
  },
  {
    title: "Orchestrator creates GitHub Issues",
    copy: "Orchestrator получает Planner handoff и через GitHub tools / gh / GitHub API создает issues, labels, Project fields, state ledger comments и worker handoffs.",
  },
  {
    title: "Issue Form is fallback",
    copy: "Structured Issue Form остается запасным путем, если у Orchestrator нет GitHub auth/tools. Это не основной пользовательский workflow.",
  },
  {
    title: "Worker packet is generated by Orchestrator",
    copy: "Worker получает только task-scoped packet: issue URL, acceptance criteria, blockers, branch, validation, security/design expectations и PR protocol.",
  },
  {
    title: "QA block is verified by Orchestrator",
    copy: "Worker прикладывает QA evidence к completion report, а Orchestrator проверяет его перед переводом GitHub Project Status в Review или Done.",
  },
  {
    title: "GitHub Pages is instruction only",
    copy: "Pages публикует правила и snippets, но не хранит секреты, не вызывает API и не заменяет Orchestrator runtime.",
  },
];

const operatingGates: Card[] = [
  {
    title: "Max worker tasks per Orchestrator Chat: 5",
    copy: "После пятой worker-задачи Orchestrator прекращает новые запуски, обновляет state ledger, переходит в DRAINING и готовит handoff YAML.",
  },
  {
    title: "Replacement takeover",
    copy: "Новый Orchestrator начинает с takeover audit: подтверждает active workers, claimed issues, branches, PR links и переводит старый Orchestrator в RETIRED после acceptance.",
  },
  {
    title: "Model Router before launch",
    copy: "Перед Worker packet Orchestrator выбирает модель и reasoning effort по risk, ambiguity, security, shared contracts и UI/design surface.",
  },
  {
    title: "Grounding before RED",
    copy: "Worker подтверждает owner layer через Graphify or fallback repository tracing до TDD RED/GREEN и фиксирует это в PR evidence.",
  },
  {
    title: "QA before Review",
    copy: "QA subagents работают read-only: test coverage и regression по умолчанию, security/UI reviewers при соответствующей поверхности.",
  },
  {
    title: "Completion evidence",
    copy: "Worker completion report включает acceptance, TDD RED/GREEN, validation, grounding, QA subagents, security/design notes и remaining risk.",
  },
];

const newProjectSteps: Step[] = [
  {
    title: "1. Создай repo и дай Orchestrator GitHub access",
    copy: "Human action на старте минимальный: нужен репозиторий и авторизованный Orchestrator с GitHub tools / gh / GitHub API. Дальше setup делает Orchestrator.",
  },
  {
    title: "2. Вставь идею и canonical md в Planner",
    copy: "Planner возвращает planner_yaml, canonical_md, orchestrator_prompt и GitHub Setup Packet: repo settings, labels, Project schema, Pages, template checks и fallback commands.",
  },
  {
    title: "3. Передай packet в Orchestrator",
    copy: "Orchestrator applies GitHub setup: проверяет gh auth status, включает Issues/Projects, создает labels, Project fields, Ready Queue rules и state ledger.",
  },
  {
    title: "4. Orchestrator проверяет repo files",
    copy: "Он проверяет AGENTS.md, docs/github-agent-workflow.md, Issue Form, PR template, Pages workflow и readiness audit. Если файлов нет, возвращает patch или запускает Worker на docs/setup task.",
  },
  {
    title: "5. Orchestrator создает первые GitHub Issues",
    copy: "После setup он создает задачи из Planner handoff, добавляет Project state, blockers, labels и генерирует Worker packets. Человек не создает delivery issues вручную.",
  },
  {
    title: "6. Manual path только как fallback",
    copy: "Если прав не хватает, Orchestrator возвращает Human action required с готовыми gh commands, issue body, labels, Project fields и Pages action.",
  },
];

const existingProjectSteps: Step[] = [
  {
    title: "1. Проведи аудит текущего проекта",
    copy: "Посмотри существующие labels, issue templates, PR template, Actions, GitHub Project views, правила branch protection и текущий формат задач. Не ломай старый процесс в первый день.",
  },
  {
    title: "2. Добавь GitHub-native guide рядом с текущими правилами",
    copy: "Сначала добавь AGENTS.md, docs/github-agent-workflow.md и PR template. Если в проекте уже есть PR template, объедини секции evidence, validation, security, design и rollout без удаления важных локальных правил.",
  },
  {
    title: "3. Сопоставь существующие статусы с новой очередью",
    copy: "Intake, Ready, In Progress, Review, Blocked и Done должны быть единственным языком для агентной очереди. Старые project views можно оставить, но Ready Queue должна быть однозначной.",
  },
  {
    title: "4. Мигрируй issues постепенно",
    copy: "Не переписывай весь backlog. Выбери 3-5 задач, приведи их к Agent task contract, добавь readiness sections и только после этого ставь agent-ready.",
  },
  {
    title: "5. Запусти pilot через один Worker PR",
    copy: "Проверь полный цикл: issue -> Project Status Ready -> Worker branch -> PR with Closes # -> validation evidence -> Review -> Done. После pilot обнови правила, которые оказались неясными.",
  },
  {
    title: "6. Зафиксируй исключения",
    copy: "Если проект имеет обязательные релизные, security или QA правила, добавь их в AGENTS.md и PR template. Orchestrator должен видеть эти правила до запуска Worker.",
  },
];

const existingLinearProjectSteps: Step[] = [
  {
    title: "1. Linear workflow audit",
    copy: "Сначала проверь Linear teams, projects, statuses, cycles, labels, templates, blockers, dependencies, ready filters и текущий linked PR flow.",
  },
  {
    title: "2. Linear-to-GitHub mapping",
    copy: "Planner сопоставляет Linear issue/status/label/blocker/project/cycle с GitHub Issue, GitHub Project Status, labels, dependencies, views и PR with Closes #.",
  },
  {
    title: "3. Transitional source of truth",
    copy: "Linear остается product/backlog source, пока migration partial. GitHub Issue становится agent task contract, GitHub Project становится execution queue.",
  },
  {
    title: "4. Mirror only pilot work",
    copy: "Не переписывай весь backlog. Выбери 3-5 Linear issues, создай или зеркаль их в GitHub Issues и сохрани Linear links в body/comments.",
  },
  {
    title: "5. Launch workers only from GitHub",
    copy: "Orchestrator не запускает Worker напрямую из Linear issue. Нужен GitHub Issue с Ready status, agent-ready label, no blockers и полными readiness fields.",
  },
  {
    title: "6. Preserve backlinks",
    copy: "GitHub Issue links back to Linear, PR links with Closes #<github-issue>, and Linear receives GitHub Issue/PR links when access allows.",
  },
];

const noToolingProjectSteps: Step[] = [
  {
    title: "1. No-tooling bootstrap audit",
    copy: "Проверь README, docs, scripts, tests, CI, deploy, branch protection expectations, .github templates и включены ли Issues, Projects, Actions и Pages.",
  },
  {
    title: "2. Planner writes GitHub Setup Packet",
    copy: "Packet должен описывать repo settings, labels, Project fields, Ready Queue, Issue Form, PR template, readiness audit, Pages setup и fallback commands.",
  },
  {
    title: "3. Orchestrator applies setup",
    copy: "Orchestrator применяет gh repo edit --enable-issues --enable-projects, gh label create, gh project field-create, template patches и setup verification.",
  },
  {
    title: "4. First issues come from Planner handoff",
    copy: "Human не создает delivery issues вручную. Orchestrator создает setup-sized issues: templates, readiness audit, CI validation и один pilot task.",
  },
  {
    title: "5. Product delivery waits for setup",
    copy: "agent-ready ставится только на задачи с полным контрактом. Product work начинается после guide, templates, labels, Project fields и PR evidence path.",
  },
  {
    title: "6. Exact fallback when access is missing",
    copy: "Если прав не хватает, Orchestrator возвращает Human action required с точными commands, patches, issue bodies, labels, Project fields и UI paths.",
  },
];

const setupPacketChecklist = [
  "Planner returns GitHub Setup Packet with repo_settings, labels, project_fields, pages, template_files, ready_queue, fallback_commands.",
  "Orchestrator applies GitHub setup after gh auth status or equivalent GitHub tool/API access check.",
  "Repo settings command: gh repo edit --enable-issues --enable-projects.",
  "Label command pattern: gh label create <name> --color <hex> --description <text> --force.",
  "Project field command pattern: gh project field-create <number> --owner <owner> --name <field> --data-type SINGLE_SELECT --single-select-options <options>.",
  "Template checks confirm Issue Form, config.yml, PR template, Pages deploy workflow, readiness audit workflow, AGENTS.md, and guide docs.",
  "Ready Queue rule stays Status = Ready + label:agent-ready + no open blockers.",
  "Manual GitHub setup is fallback only when Orchestrator lacks permissions.",
  "Human action required must include exact commands, issue body, labels, Project fields, and Pages action.",
  "Worker PR rule remains one issue, one branch, one PR, linked with Closes #123.",
];

const setupCommands = `# Orchestrator applies GitHub setup
gh auth status
gh repo edit --enable-issues --enable-projects

gh label create agent-ready --color 35f2a3 --description "Ready for agent worker" --force
gh label create blocked --color ff6d91 --description "Blocked by dependency or decision" --force
gh label create qa-required --color ffc86b --description "Requires QA evidence before Done" --force

gh project field-create <project-number> --owner <owner> --name Status --data-type SINGLE_SELECT --single-select-options "Intake,Ready,In Progress,Review,Blocked,Done"
gh project field-create <project-number> --owner <owner> --name "Work Type" --data-type SINGLE_SELECT --single-select-options "Guide,Template,Automation,Site,Docs"
gh project field-create <project-number> --owner <owner> --name Risk --data-type SINGLE_SELECT --single-select-options "Low,Medium,High"
gh project field-create <project-number> --owner <owner> --name "QA Required" --data-type SINGLE_SELECT --single-select-options "Yes,No"`;

const templateFiles: Card[] = [
  {
    title: "AGENTS.md",
    copy: "Project-specific rules for Planner, Orchestrator, Worker, readiness gate, branch naming, PR evidence, Pages limits, and validation.",
  },
  {
    title: "agent-task.yml",
    copy: "Structured Issue Form that captures goal, acceptance criteria, blockers, validation, security, design, and QA requirement.",
  },
  {
    title: "pull_request_template.md",
    copy: "Evidence package for linked issue, acceptance proof, TDD/docs exemption, validation, security, design, grounding, risks, and rollout.",
  },
  {
    title: "readiness-audit.yml",
    copy: "Optional GitHub Action that comments when agent-ready is applied before required readiness sections exist.",
  },
];

const prompts: PromptBlock[] = [
  {
    title: "Brainstorm prompt",
    copy: "Первый чат, который человек создает вручную. Он формирует idea summary для Planner.",
    prompt: `Ты Brainstorm Chat для GitHub-native agent workflow.

Задача:
- помочь сформулировать идею;
- уточнить цель, аудиторию, ограничения, risks и out of scope;
- собрать 3-5 observable acceptance criteria;
- определить blockers/dependencies;
- описать validation expectations;
- отметить security, UI/design и QA impact.

Не создавай GitHub Issues. Не запускай Worker Chat.

Верни concise idea summary, который человек вставит в Planner Chat вместе с canonical GitHub workflow.`,
  },
  {
    title: "Planner setup prompt",
    copy: "Используй один раз при создании или обновлении процесса в репозитории.",
    prompt: `Ты Planner Chat для GitHub-native agent workflow.

Открой репозиторий и используй GitHub как source of truth. Проверь AGENTS.md, docs/github-agent-workflow.md, Issue Forms, PR template, labels, GitHub Project fields, Actions и Pages workflow.

Human creates only Brainstorm Chat, Planner Chat, and Orchestrator Chat.

Задача:
1. Настрой или обнови workflow так, чтобы он работал без Linear.
2. Проверь, что GitHub Issue является контрактом задачи.
3. Подготовь Orchestrator seed packet, чтобы Orchestrator creates GitHub Issues через GitHub tools / gh / GitHub API.
4. Подготовь GitHub Setup Packet: repo_settings, labels, project_fields, ready_queue, pages, template_files, fallback_commands.
5. Не создавай Worker Chats и не выполняй delivery work.

Верни:
- какие файлы/настройки изменены;
- GitHub Setup Packet с командами gh repo edit --enable-issues --enable-projects, gh label create и gh project field-create;
- Orchestrator seed packet;
- какие future issues можно создать автоматически;
- какие work items blocked и почему;
- какие решения должен принять человек.`,
  },
  {
    title: "Orchestrator queue prompt",
    copy: "Главный execution чат. Он создает GitHub Issues/Project state и генерирует Worker packets.",
    prompt: `Ты Orchestrator Chat для GitHub-native agent workflow.

Используй только GitHub state: Issues, Project fields, labels, dependencies/sub-issues, linked PRs, comments, Actions и repository files.

Вход:
- canonical GitHub workflow;
- Planner handoff / seed packet;
- GitHub Setup Packet;
- repo and project configuration.

Твоя задача:
1. Orchestrator applies GitHub setup: проверь gh auth status, затем примени repo settings, labels, Project fields, Pages checks и template checks из packet.
2. Используй gh repo edit --enable-issues --enable-projects для repo settings, gh label create --force для labels и gh project field-create для Project fields, если доступны права.
3. Создать или обновить GitHub Issues через GitHub tools / gh / GitHub API.
4. Добавить labels и GitHub Project fields.
5. Построить dependency graph по blockers/sub-issues/linked PRs.
6. Применить readiness gate.
7. Запустить heartbeat every 20-30 minutes и вести state ledger в GitHub issue comments или Project updates.
8. Перед каждым Worker вызвать Model Router и выбрать model/reasoning effort.
9. Сгенерировать task-scoped Worker packet.
10. Соблюдать Max worker tasks per Orchestrator Chat: 5.
11. После пятой worker-задачи перейти в DRAINING, создать handoff YAML и запустить replacement Orchestrator или вернуть Human action required.
12. Проверить QA block перед переводом в Review или Done.

Ready gate:
- Project Status = Ready;
- есть label agent-ready;
- нет открытых blockers;
- issue body содержит Goal, Acceptance Criteria, Dependency / Blocker State, Validation Expectations, Security Impact, UI / Design Impact и QA Requirement.
- issue body содержит Model Router, Graphify or fallback repository tracing, TDD RED/GREEN, QA subagents и Primary signal.

Issue Form is fallback: если GitHub tools/API недоступны, верни Human action required с готовым issue body, labels, Project fields, Pages action и gh commands.

Не выполняй production code. Не делай delivery сам.

Верни setup_report, created/updated issue URLs, Project state, Worker packet, task count, handoff status и краткий state ledger comment.`,
  },
  {
    title: "Worker delivery prompt",
    copy: "Reference only: этот блок человек обычно не копирует вручную.",
    prompt: `Этот блок человек обычно НЕ копирует вручную.
Worker packet is generated by Orchestrator.

Ты Worker Chat для GitHub-native agent workflow.

Возьми только GitHub Issue #<номер>. Не расширяй scope.

Перед кодом:
1. Прочитай issue body, comments, labels, Project fields, blockers, linked PRs, AGENTS.md и релевантные docs.
2. Подтверди, что Ready gate выполнен: Project Status = Ready + label agent-ready + нет blockers.
3. Подтверди Graphify or fallback repository tracing и owner layer до RED.
4. Создай одну branch: feat/<issue>-short-slug, fix/<issue>-short-slug или docs/<issue>-short-slug.

Delivery:
1. Сделай TDD RED/GREEN: сначала failing test, затем минимальный implementation, затем refactor только после green.
2. Сделай минимальное изменение, которое закрывает acceptance criteria.
3. Запусти validation из issue и ближайшие дешевые проверки проекта.
4. Запусти QA subagents read-only перед READY_FOR_REVIEW: test coverage, regression, security/UI reviewers when applicable.
5. Открой один PR с Closes #<номер>.
6. Заполни PR template evidence: acceptance, TDD RED/GREEN, validation, security, design, Graphify or fallback repository tracing, QA subagents, risks, rollout.

Не закрывай задачу без validation evidence и Worker completion report.`,
  },
  {
    title: "QA verification block",
    copy: "Reference only: Worker заполняет evidence, Orchestrator проверяет перед Review/Done.",
    prompt: `Этот блок человек обычно НЕ копирует вручную.
QA block is verified by Orchestrator before GitHub Project Status moves to Review or Done.

QA evidence:
- Tests run:
- Regression risk:
- Security review:
- UI/design review:
- Findings:
- Findings resolved:
- Remaining risk:`,
  },
  {
    title: "Existing project migration prompt",
    copy: "Используй для аккуратного внедрения в проект, где уже есть свои labels, шаблоны и CI.",
    prompt: `Ты Planner Chat. Нужно внедрить GitHub-native agent workflow в существующий проект без поломки текущего процесса.

Сначала прочитай README, AGENTS.md если есть, .github templates, workflows, current labels, Project views и branch protection expectations.

Сделай migration plan:
1. Что можно добавить без риска.
2. Что нужно объединить с текущими шаблонами.
3. Какие старые labels/statuses мапятся на Intake, Ready, In Progress, Review, Blocked, Done.
4. Какие 3-5 issues лучше взять для pilot.
5. Какие team-specific правила нужно добавить в AGENTS.md и PR template.

Не удаляй существующие правила без явного решения человека.`,
  },
  {
    title: "Existing Linear project prompt",
    copy: "Используй для проекта, где backlog и продуктовая очередь уже живут в Linear.",
    prompt: `Ты Planner Chat. Нужно внедрить GitHub-native agent workflow в проект, который уже работает через Linear.

Сначала сделай Linear workflow audit:
- Linear teams/projects/statuses/cycles/labels/templates;
- текущие ready filters, blockers, dependencies и linked PR flow;
- кто принимает product priority, acceptance, release и QA решения;
- какие Linear поля обязательны до разработки.

Затем сделай Linear-to-GitHub mapping:
- Linear issue -> GitHub Issue;
- Linear status -> GitHub Project Status;
- Linear label -> GitHub label;
- Linear dependency/blocker -> GitHub dependency, sub-issue или blocker link;
- Linear project/cycle -> GitHub Project view, milestone или label;
- Linear linked PR -> GitHub PR with Closes #<github-issue> and Linear backlink.

Правила:
1. Не переписывай весь Linear backlog.
2. Выбери 3-5 Linear issues для pilot.
3. Для каждой pilot-задачи создай или опиши GitHub Issue с полным Agent task contract.
4. Linear остается product/backlog source, пока migration partial.
5. GitHub Issue и GitHub Project становятся execution source для agent delivery.
6. Orchestrator не запускает Worker напрямую из Linear issue.
7. Если не хватает доступа, верни Human action required с точными Linear URLs, GitHub issue bodies, labels, Project fields и comments.

Верни GitHub Setup Packet, Linear-to-GitHub mapping, pilot issue list, transitional source of truth и Orchestrator seed packet.`,
  },
  {
    title: "No-tooling bootstrap prompt",
    copy: "Используй для проекта без Linear, GitHub Project queue, agent-ready labels и агентного процесса.",
    prompt: `Ты Planner Chat. Нужно внедрить GitHub-native agent workflow в проект, где вообще нет Linear, GitHub Project queue, agent-ready labels или агентного процесса.

Это No-tooling bootstrap. Сначала создается operating system, потом product delivery.

Сначала прочитай:
- README.md и docs;
- AGENTS.md если есть;
- .github templates/workflows если есть;
- package manager, scripts, tests, build, lint, deploy;
- branch protection/release expectations, если они описаны;
- включены ли Issues, Projects, Actions и Pages.

Сделай GitHub Setup Packet:
- repo_settings: issues/projects/pages/actions;
- labels: agent-ready, blocked, qa-required, security-review, design-review, docs, automation, github-pages, workflow;
- project_fields: Status, Work Type, Risk, QA Required;
- ready_queue: Status = Ready + label:agent-ready + no open blockers;
- template_files: AGENTS.md, docs/github-agent-workflow.md, Issue Form, PR template, readiness audit, Pages workflow if needed;
- fallback_commands: exact gh/API/UI actions.

Правила:
1. Первые GitHub Issues создает Orchestrator из Planner handoff.
2. Human не проектирует issue bodies вручную.
3. Первые задачи должны быть setup-sized: templates, readiness audit, CI validation, one pilot issue.
4. Product delivery начинается только после setup verification.
5. Если доступа нет, верни Human action required с точными командами, patches, issue bodies, labels, Project fields и UI paths.

Верни GitHub Setup Packet, Orchestrator seed packet, first setup issues, validation commands и blocked access list.`,
  },
];

function HeroVisual() {
  const [webgl, setWebgl] = useState(false);
  const posterUrl = useMemo(() => `${import.meta.env.BASE_URL}images/sculpture-poster.png`, []);

  useEffect(() => {
    setWebgl(supportsWebGL());
  }, []);

  return (
    <div className="hero-visual" aria-label="Abstract dark 3D sculpture representing the GitHub-native workflow">
      <img className="hero-poster" src={posterUrl} alt="" loading="eager" />
      {webgl ? (
        <Suspense fallback={null}>
          <div className="three-layer">
            <ThreeHeroCanvas />
          </div>
        </Suspense>
      ) : null}
      <div className="metadata-panel">
        <span>Ready filter</span>
        <strong>Status = Ready + agent-ready</strong>
      </div>
    </div>
  );
}

function App() {
  const [canonicalCopied, setCanonicalCopied] = useState(false);

  function copyCanonicalMarkdown() {
    const copy = navigator.clipboard?.writeText
      ? navigator.clipboard.writeText(canonicalMarkdown)
      : Promise.reject(new Error("clipboard unavailable"));

    copy
      .catch(() => {
        const area = document.createElement("textarea");
        area.value = canonicalMarkdown;
        area.setAttribute("readonly", "");
        area.style.position = "fixed";
        area.style.top = "-9999px";
        document.body.appendChild(area);
        area.focus();
        area.select();
        document.execCommand("copy");
        document.body.removeChild(area);
      })
      .then(() => {
        setCanonicalCopied(true);
        window.setTimeout(() => setCanonicalCopied(false), 1400);
      });
  }

  return (
    <main>
      <header className="site-header">
        <a className="brand" href="#top" aria-label="GitHub-native agent workflow home">
          GH Agent OS
        </a>
        <nav aria-label="Primary navigation">
          <a href="#model">Model</a>
          <a href="#automation">Automation</a>
          <a href="#setup">Setup</a>
          <a href="#gate">Gate</a>
          <a href="#operations">Operations</a>
          <a href="#canonical">Canonical</a>
          <a href="#prompts">Prompts</a>
          <a href="#stack">Stack</a>
          <a href="https://github.com/nazarKuznetsov/agent_workflow_guide_github_solutions">GitHub</a>
        </nav>
      </header>

      <section className="hero section-band" id="top">
        <div className="hero-copy">
          <p className="eyebrow">GitHub-native agent workflow / GitHub Pages ready</p>
          <h1>GitHub-native agent workflow</h1>
          <p className="hero-lede">
            A presentable operating guide for replacing a Linear-centered agent queue with GitHub Issues,
            GitHub Projects, Issue Forms, labels, PR templates, GitHub Actions, API automation, and GitHub Pages.
          </p>
          <div className="hero-actions">
            <a className="button primary" href="#automation">
              View automation
            </a>
            <a className="button secondary" href="#prompts">
              Copy prompts
            </a>
          </div>
          <dl className="status-strip" aria-label="Workflow status summary">
            <div>
              <dt>Source</dt>
              <dd>GitHub Issues</dd>
            </div>
            <div>
              <dt>Queue</dt>
              <dd>GitHub Projects</dd>
            </div>
            <div>
              <dt>Publish</dt>
              <dd>GitHub Pages</dd>
            </div>
          </dl>
        </div>
        <HeroVisual />
      </section>

      <section className="positioning section-band" id="model">
        <h2>One GitHub stack replaces the planning handoff.</h2>
        <p>
          The workflow keeps agent roles explicit. Planner Chat shapes the operating rules, Orchestrator Chat reads
          the GitHub Project queue and blocker state, and Worker Chat delivers exactly one GitHub Issue through one
          branch and one pull request.
        </p>
      </section>

      <section className="setup-playbook section-band" id="automation">
        <div className="section-heading">
          <p className="eyebrow">Linear-like GitHub automation</p>
          <h2>Human creates only Brainstorm Chat, Planner Chat, and Orchestrator Chat.</h2>
          <p>
            GitHub Pages is the instruction layer. The runtime automation lives in Orchestrator Chat, which uses
            GitHub tools / gh / GitHub API to create issues, project state, worker packets, and review gates.
          </p>
        </div>
        <div className="setup-grid">
          {controlPlane.map((step) => (
            <article className="setup-card" key={step.title}>
              <h3>{step.title}</h3>
              <p>{step.copy}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="section-band" id="gate">
        <div className="section-heading">
          <p className="eyebrow">Readiness gate</p>
          <h2>Ready means observable, not aspirational.</h2>
        </div>
        <div className="gate-grid">
          <article className="gate-card strong">
            <span>Default filter</span>
            <strong>Project Status = Ready</strong>
            <strong>label: agent-ready</strong>
            <p>No open blockers, complete acceptance criteria, validation expectations, and security/design notes.</p>
          </article>
          <article className="gate-card">
            <span>Stop condition</span>
            <p>
              Missing readiness fields, unresolved dependencies, multiple PR-sized changes, or unapproved risky
              decisions move the issue back out of Ready.
            </p>
          </article>
          <article className="gate-card">
            <span>State ledger</span>
            <p>
              Orchestrator records queue moves, blocker decisions, worker starts, PR links, and completion evidence in
              GitHub issue comments or Project updates.
            </p>
          </article>
        </div>
      </section>

      <section className="setup-playbook section-band" id="operations">
        <div className="section-heading">
          <p className="eyebrow">Operational lifecycle</p>
          <h2>GitHub-native Orchestrator keeps the Linear discipline.</h2>
          <p>
            The queue lives in GitHub, but the coordination rules stay strict: heartbeat every 20-30 minutes, Model
            Router before launch, task-scoped Worker packets, handoff YAML at budget, and evidence checks before Review
            or Done.
          </p>
        </div>
        <div className="setup-grid">
          {operatingGates.map((gate) => (
            <article className="setup-card" key={gate.title}>
              <h3>{gate.title}</h3>
              <p>{gate.copy}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="section-band" id="stack">
        <div className="section-heading">
          <p className="eyebrow">Template stack</p>
          <h2>The workflow is encoded where the team already works.</h2>
        </div>
        <div className="capability-grid">
          {capabilities.map((card) => (
            <article className="capability-card" key={card.title}>
              <h3>{card.title}</h3>
              <p>{card.copy}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="process section-band">
        <div className="section-heading">
          <p className="eyebrow">Operating flow</p>
          <h2>Planner, Orchestrator, Worker, PR.</h2>
        </div>
        <ol>
          {flow.map(([number, title, copy]) => (
            <li key={number}>
              <span>{number}</span>
              <div>
                <h3>{title}</h3>
                <p>{copy}</p>
              </div>
            </li>
          ))}
        </ol>
      </section>

      <section className="proof section-band">
        <div className="terminal-card" aria-label="Recommended GitHub Project schema">
          <span className="terminal-label">GitHub Project schema</span>
          <pre>{`Status: Intake, Ready, In Progress, Review, Blocked, Done
Work Type: Guide, Template, Automation, Site, Docs
Risk: Low, Medium, High
QA Required: Yes, No

Ready view:
Status = Ready
label:agent-ready
no open blockers`}</pre>
        </div>
        <div className="pages-answer">
          <p className="eyebrow">GitHub Pages answer</p>
          <h2>Yes, publish the instruction on GitHub Pages.</h2>
          <p>
            GitHub Pages can host this presentation because it is static. It should not store secrets, run private
            orchestration, or replace the GitHub Issue and Project state model.
          </p>
        </div>
      </section>

      <section className="setup-playbook section-band" id="setup">
        <div className="section-heading">
          <p className="eyebrow">Self-contained setup guide</p>
          <h2>New project setup / настройка нового проекта.</h2>
          <p>
            Используй этот блок как пошаговую инструкцию: сначала включи GitHub-функции, затем скопируй шаблоны,
            создай Project schema и только после этого запускай агентную очередь.
          </p>
        </div>
        <div className="setup-grid">
          {newProjectSteps.map((step) => (
            <article className="setup-card" key={step.title}>
              <h3>{step.title}</h3>
              <p>{step.copy}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="canonical-section section-band" id="canonical">
        <div className="section-heading">
          <p className="eyebrow">Canonical MD</p>
          <h2>Canonical MD template</h2>
          <p>
            This is the full GitHub-native canonical workflow markdown from docs/github-agent-workflow.md. Copy it into
            Planner or Orchestrator when you need the same operating source that the repository stores.
          </p>
        </div>
        <article className="canonical-block">
          <div className="canonical-head">
            <h3>Full canonical GitHub workflow markdown</h3>
            <button className="copy-button" type="button" onClick={copyCanonicalMarkdown}>
              {canonicalCopied ? "Copied" : "Copy"}
            </button>
          </div>
          <textarea
            className="canonical-source"
            readOnly
            spellCheck={false}
            aria-label="Full canonical GitHub workflow markdown"
            value={canonicalMarkdown}
          />
        </article>
      </section>

      <section className="setup-playbook section-band">
        <div className="section-heading">
          <p className="eyebrow">Migration path</p>
          <h2>Existing project integration / внедрение в готовый проект.</h2>
          <p>
            В существующем проекте задача не в том, чтобы переписать backlog. Сначала вводится единый ready gate,
            затем пилотируется один полный цикл issue to PR to Done.
          </p>
        </div>
        <div className="setup-grid">
          {existingProjectSteps.map((step) => (
            <article className="setup-card" key={step.title}>
              <h3>{step.title}</h3>
              <p>{step.copy}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="setup-playbook section-band">
        <div className="section-heading">
          <p className="eyebrow">Linear adoption path</p>
          <h2>Existing project with Linear.</h2>
          <p>
            Если продуктовая очередь уже в Linear, не удаляй ее сразу. Сначала зафиксируй Linear workflow audit,
            сделай Linear-to-GitHub mapping и запускай Workers только из mirrored GitHub Issues.
          </p>
        </div>
        <div className="setup-grid">
          {existingLinearProjectSteps.map((step) => (
            <article className="setup-card" key={step.title}>
              <h3>{step.title}</h3>
              <p>{step.copy}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="setup-playbook section-band">
        <div className="section-heading">
          <p className="eyebrow">Bootstrap path</p>
          <h2>Existing project without agent workflow.</h2>
          <p>
            Если нет Linear, GitHub Project queue, labels или шаблонов, начинай с No-tooling bootstrap: Planner пишет
            GitHub Setup Packet, Orchestrator applies setup, и только потом появляется первый pilot Worker PR.
          </p>
        </div>
        <div className="setup-grid">
          {noToolingProjectSteps.map((step) => (
            <article className="setup-card" key={step.title}>
              <h3>{step.title}</h3>
              <p>{step.copy}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="checklist section-band">
        <div className="section-heading">
          <p className="eyebrow">Automated GitHub setup</p>
          <h2>GitHub Setup Packet: Planner пишет, Orchestrator применяет.</h2>
          <p>
            В нормальном потоке человек не создает labels, Project fields и delivery issues руками. Planner генерирует
            packet, Orchestrator applies GitHub setup, а ручной блок появляется только как Human action required.
          </p>
        </div>
        <div className="checklist-grid">
          <div className="checklist-panel">
            <h3>Automated setup contract</h3>
            <ul>
              {setupPacketChecklist.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </div>
          <div className="checklist-panel">
            <h3>Orchestrator command surface</h3>
            <pre>{setupCommands}</pre>
          </div>
        </div>
        <div className="checklist-grid">
          <div className="checklist-panel">
            <h3>Files Orchestrator verifies</h3>
            <div className="file-list">
              {templateFiles.map((file) => (
                <div key={file.title}>
                  <strong>{file.title}</strong>
                  <p>{file.copy}</p>
                </div>
              ))}
            </div>
          </div>
          <div className="checklist-panel">
            <h3>Fallback rule</h3>
            <p>
              Manual GitHub setup is fallback. If Orchestrator cannot mutate the repository or Project, it returns
              Human action required with exact `gh` commands, issue body, labels, Project fields, Pages source action,
              and the reason automation was blocked.
            </p>
          </div>
        </div>
      </section>

      <section className="prompts section-band" id="prompts">
        <div className="section-heading">
          <p className="eyebrow">Copy/paste prompts</p>
          <h2>Готовые промпты для Planner, Orchestrator и Worker.</h2>
          <p>
            Эти тексты можно вставлять в агентные чаты. Они принуждают агента читать GitHub-состояние, не работать по
            памяти и не запускать delivery до прохождения readiness gate.
          </p>
        </div>
        <div className="prompt-grid">
          {prompts.map((prompt) => (
            <article className="prompt-card" key={prompt.title}>
              <div>
                <h3>{prompt.title}</h3>
                <p>{prompt.copy}</p>
              </div>
              <pre>{prompt.prompt}</pre>
            </article>
          ))}
        </div>
      </section>

      <section className="final-cta section-band">
        <p className="eyebrow">Migration checklist</p>
        <h2>Открой Brainstorm, Planner и Orchestrator; дальше Orchestrator ведет GitHub queue.</h2>
        <a className="button primary" href="https://github.com/nazarKuznetsov/agent_workflow_guide_github_solutions/issues/new/choose">
          Fallback issue form
        </a>
      </section>

      <footer className="site-footer">
        <span>Static-first. GitHub-native. Pages-safe.</span>
        <a href="https://github.com/nazarKuznetsov/agent_workflow_guide_github_solutions">Repository</a>
      </footer>
    </main>
  );
}

export default App;
